/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import service.IMotorCarService;
import web.form.AddBackRecordForm;

import common.exception.MotorbikeCarException;
import common.util.BeanFactory;

/**
 * MyEclipse Struts Creation date: 05-11-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/addBackRecord" name="addBackRecordForm"
 *                input="/pages/car/backrecord.jsp" scope="request"
 * @struts.action-forward name="failure" path="/pages/car/backrecord.jsp"
 *                        redirect="true"
 */
public class AddBackRecordAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm f,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session=request.getSession();
		AddBackRecordForm form = (AddBackRecordForm) f;
		long outid = form.getId();
		String backdate = form.getBackdate();
		long day = form.getDay();
		long cost = form.getCost();
		IMotorCarService service = (IMotorCarService) BeanFactory
				.getBean("motorcarService");
		try {
			service.addBackRecord(outid, backdate, day, cost);
			session.setAttribute("message", "操作成功");
			return mapping.findForward("success");
		} catch (MotorbikeCarException e) {
			session.setAttribute("message", e.getMessage());
			e.printStackTrace();
			return mapping.findForward("failure");
		}
	}
}