/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import common.exception.UserException;
import common.util.BeanFactory;
import dao.bean.Driver;
import dao.bean.MotorCar;
import dao.bean.User;

import service.IMotorCarService;
import service.IUserService;

import web.form.AddCarForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-20-2002
 * 
 * XDoclet definition:
 * @struts.action path="/addCar" name="addCarForm" input="/pages/car/addcar.jsp" scope="request"
 * @struts.action-forward name="success" path="/pages/car/addcar.jsp" redirect="true"
 */
public class AddCarAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddCarForm addform = (AddCarForm) form;
		HttpSession session=request.getSession();
		User user=(User) session.getAttribute("user");
		if(user.getPower()!=2){
			session.setAttribute("message", "对不起,您的权限不够!");
			return mapping.findForward("success");
		}
		String carnumber=addform.getCarnumber();
		String cartype=addform.getCartype();
		String drivername=addform.getDriver();
		long capacity=addform.getCapacity();
		String registerdate=addform.getRegisterdate();
		String regman=addform.getRegman();
		String descripe=addform.getDescripe();
		MotorCar car=new MotorCar();
		car.setCarnumber(carnumber);
		car.setCartype(cartype);
		car.setCapacity(capacity);
		car.setRegisterdate(registerdate);
		car.setDescripe(descripe);
		car.setStatus("待命");
		
		IUserService service=(IUserService)BeanFactory.getBean("userService");
		try {
			Driver driver=service.findDriver(drivername);
			if(driver==null){
				session.setAttribute("message", "您输入的驾驶员不存在");
				return mapping.findForward("success");
			}
			car.setDriver(driver);
			IMotorCarService carservice = (IMotorCarService) BeanFactory
					.getBean("motorcarService");
			carservice.addMotorCar(car);
		} catch (Exception e) {
			e.printStackTrace();
			session.setAttribute("message", e.getMessage());
			return mapping.findForward("success");
		}
		session.setAttribute("message", "操作成功");
		return mapping.findForward("success");
	}
}