/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import common.exception.UserException;
import common.util.BeanFactory;

import service.IMotorCarService;
import service.IUserService;

import web.form.AddEmployeeForm;
import dao.bean.Driver;
import dao.bean.User;

/** 
 * MyEclipse Struts
 * Creation date: 04-20-2002
 * 
 * XDoclet definition:
 * @struts.action path="/addEmployee" name="addEmployeeForm" input="/pages/member/addemployee.jsp" scope="request"
 * @struts.action-forward name="success" path="/pages/member/addemployee.jsp" redirect="true"
 */
public class AddEmployeeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddEmployeeForm addform = (AddEmployeeForm) form;
		HttpSession session=request.getSession();
		User user=(User) session.getAttribute("user");
		if(user.getPower()!=2){
			session.setAttribute("message", "对不起，您的权限不够");
			return mapping.findForward("success");
		}
		String name=addform.getName();
		String gender=addform.getGender();
		long age=addform.getAge();
		String educationlevel=addform.getEducationlevel();
		String position=addform.getPosition();
		String licensenum=addform.getLicensenum();
		String cartype=addform.getCartype();
		String address=addform.getAddress();
		String phone=addform.getPhone();
		String descripe=addform.getDescripe();
		Driver driver=new Driver();
		driver.setName(name);
		driver.setGender(gender);
		driver.setAge(age);
		driver.setEducationlevel(educationlevel);
		driver.setPosition(position);
		driver.setLicensenum(licensenum);
		driver.setCartype(cartype);
		driver.setAddress(address);
		driver.setPhone(phone);
		driver.setDescripe(descripe);
		IUserService service = (IUserService) BeanFactory
				.getBean("userService");
		try {
			service.addDriver(driver);
		} catch (UserException e) {
			e.printStackTrace();
			session.setAttribute("message", e.getMessage());
			return mapping.findForward("success");
		}
		session.setAttribute("message", "操作成功");
		return mapping.findForward("success");
	}
}