/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import service.IMotorCarService;
import web.form.FindCarsForm;

import common.exception.MotorbikeCarException;
import common.util.BeanFactory;
import dao.bean.MotorCar;

/** 
 * MyEclipse Struts
 * Creation date: 05-09-2008
 * 
 * XDoclet definition:
 * @struts.action path="/findCarsByCondition" name="findCarsForm" input="/pages/car/carstatus.jsp" scope="request"
 * @struts.action-forward name="success" path="/pages/car/carstatus.jsp" redirect="true"
 */
public class FindCarsByConditionAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FindCarsForm findform = (FindCarsForm) form;
		HttpSession session=request.getSession();
		String cartype=findform.getCartype();
		String status=findform.getStatus();
		IMotorCarService service = (IMotorCarService) BeanFactory
				.getBean("motorcarService");
		try {
			List<MotorCar> list=service.findCarByCondition(cartype, status);
			session.setAttribute("carlist", list);
		} catch (MotorbikeCarException e) {
			e.printStackTrace();
		}		
		return mapping.findForward("success");
	}
}