/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import common.exception.MotorbikeCarException;
import common.util.BeanFactory;
import dao.bean.ApplicationRecord;

import service.IMotorCarService;

/** 
 * MyEclipse Struts
 * Creation date: 05-10-2008
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="success" path="/pages/car/endorsement.jsp" redirect="true"
 */
public class FindOneAppAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session=request.getSession();
		long id=Long.parseLong(request.getParameter("appid"));
		IMotorCarService service = (IMotorCarService) BeanFactory
				.getBean("motorcarService");
		try {
			ApplicationRecord record=service.findAppById(id);
			session.setAttribute("apprecord", record);
			return mapping.findForward("success");
		} catch (MotorbikeCarException e) {
			e.printStackTrace();
			return null;
		}
	}
}