/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import service.IUserService;
import web.form.FindDriverByConditionForm;

import common.exception.UserException;
import common.util.BeanFactory;

import dao.bean.Driver;

/** 
 * MyEclipse Struts
 * Creation date: 05-23-2008
 * 
 * XDoclet definition:
 * @struts.action path="/findDriverByCondition" name="findDriverByConditionForm" input="/pages/member/driverlist.jsp" scope="request"
 * @struts.action-forward name="success" path="/pages/member/driverlist.jsp" redirect="true"
 */
public class FindDriverByConditionAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm f,
			HttpServletRequest request, HttpServletResponse response) {
		FindDriverByConditionForm form = (FindDriverByConditionForm) f;
		HttpSession session=request.getSession();
		String gender=form.getGender();
		String age=form.getAge();
		String cartype=form.getCartype();
		IUserService service=(IUserService) BeanFactory.getBean("userService");
		try {
			List<Driver> list=service.findDriverByCondition(gender, age, cartype);
			session.setAttribute("driverlist", list);
			
		} catch (UserException e) {
			e.printStackTrace();
			session.setAttribute("message", e.getMessage());
		}
		return mapping.findForward("success");
	}
}