/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import service.IUserService;

import common.exception.UserException;
import common.util.BeanFactory;

import dao.bean.User;

/**
 * MyEclipse Struts Creation date: 04-19-2002
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/pages/member/powermanage.jsp"
 *                        redirect="true"
 * @struts.action-forward name="failure" path="/pages/member/activity.jsp"
 *                        redirect="true"
 */
public class FindAllUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session = request.getSession();
		User user = (User) session.getAttribute("user");
		if (user.getPower() != 2) {
			session.setAttribute("message", "对不起，您权限不够");
			return mapping.findForward("failure");
		}
		IUserService service = (IUserService) BeanFactory
				.getBean("userService");
		try {
			List<User> list=service.findAllUser();
			User u=(User)session.getAttribute("user");
			for(int i=0;i<list.size();i++){
				if(u.getNickname().equals(list.get(i).getNickname()))
					list.remove(i);
			}
			session.setAttribute("userlist",list);
			return mapping.findForward("success");
		} catch (UserException e) {
			e.printStackTrace();
			session.setAttribute("message", e.getMessage());
			return mapping.findForward("failure");
		}
	}
}