/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import service.IUserService;
import web.form.FindMissingPasswordForm;

import common.exception.UserException;
import common.util.BeanFactory;

/** 
 * MyEclipse Struts
 * Creation date: 05-23-2008
 * 
 * XDoclet definition:
 * @struts.action path="/findMissingPassword" name="FindMissingPasswordForm" input="/pages/passwd_missing.jsp" scope="request"
 * @struts.action-forward name="success" path="/pages/login.jsp" redirect="true"
 * @struts.action-forward name="failure" path="/pages/passwd_missing.jsp" redirect="true"
 */
public class FindMissingPasswordAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm f,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session=request.getSession();
		FindMissingPasswordForm form = (FindMissingPasswordForm) f;
		String username=form.getUserName();
		String question=form.getPasswdQuestion();
		String answer=form.getPasswdAnswer();
		IUserService service=(IUserService) BeanFactory.getBean("userService");
		try {
			String password=service.findMissingPassword(username, question, answer);
			session.setAttribute("message","您的新密码为:"+password);
			return mapping.findForward("success");
		} catch (UserException e) {
			e.printStackTrace();
			session.setAttribute("message", e.getMessage());
			return mapping.findForward("failure");
		}
	}
}