/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.tools.ant.taskdefs.condition.Http;

import common.exception.MotorbikeCarException;
import common.util.BeanFactory;
import dao.bean.MotorCar;

import service.IMotorCarService;

/**
 * MyEclipse Struts Creation date: 04-21-2002
 * 
 * XDoclet definition:
 * 
 * @struts.action
 * @struts.action-forward name="success" path="/pages/car/carinfo.jsp"
 *                        redirect="true"
 */
public class FindOneCarAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		long id = Long.parseLong(request.getParameter("id"));
		HttpSession session = request.getSession();
		IMotorCarService service = (IMotorCarService) BeanFactory
				.getBean("motorcarService");
		try {
			MotorCar car=service.findOneCar(id);
			session.setAttribute("car",car);
		} catch (MotorbikeCarException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("success");
	}
}