/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import service.IUserService;

import common.exception.UserException;
import common.util.BeanFactory;

import dao.bean.Driver;

/** 
 * MyEclipse Struts
 * Creation date: 05-17-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/pages/member/driverinfo.jsp" redirect="true"
 */
public class FindDriverInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session=request.getSession();
		System.out.println("driverid="+request.getParameter("driverid"));
		long id=Long.parseLong(request.getParameter("driverid"));
		IUserService service=(IUserService) BeanFactory.getBean("userService");
		try {
			Driver driver=service.findDriverById(id);
			session.setAttribute("driver", driver);
		} catch (UserException e) {
			e.printStackTrace();
			session.setAttribute("message", e.getMessage());
		}
		return mapping.findForward("success");
	}
}