/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import service.IMotorCarService;

import common.exception.MotorbikeCarException;
import common.util.BeanFactory;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2002
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/pages/car/carlist.jsp" redirect="true"
 */
public class FindAllCarAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session=request.getSession();
		IMotorCarService service=(IMotorCarService)BeanFactory.getBean("motorcarService");
		try {
			List list=service.findAllCar();
			session.setAttribute("carlist", list);
		} catch (MotorbikeCarException e) {
			e.printStackTrace();
		}
		return mapping.findForward("success");
	}
}