/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import service.IMotorCarService;

import common.exception.MotorbikeCarException;
import common.util.BeanFactory;

import dao.bean.BackRecord;

/** 
 * MyEclipse Struts
 * Creation date: 05-17-2008
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="success" path="/pages/car/backrecordinfo.jsp" redirect="true"
 */
public class LookBackRecordInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session=request.getSession();
		long id=Long.parseLong(request.getParameter("outid"));
		IMotorCarService service = (IMotorCarService) BeanFactory
				.getBean("motorcarService");
		try {
			BackRecord record=service.findBackRecordById(id);
			session.setAttribute("backrecord", record);
		} catch (MotorbikeCarException e) {
			e.printStackTrace();
			session.setAttribute("message", e.getMessage());
		}
		
		return mapping.findForward("success");
	}
}