package dao.bean;
// default package

import java.util.Date;



/**
 * BackRecord generated by MyEclipse - Hibernate Tools
 */

public class BackRecord  implements java.io.Serializable {


    // Fields    

     private long outid;
     private OutRecord outrecord;
     private String backdate;
     private long day;
     private long cost;


    // Constructors

    /** default constructor */
    public BackRecord() {
    }

	/** minimal constructor */
    public BackRecord(OutRecord outrecord, String backdate) {
        this.outrecord = outrecord;
        this.backdate = backdate;
    }
    
    /** full constructor */
    public BackRecord(OutRecord outrecord, String backdate, long day, long cost) {
        this.outrecord = outrecord;
        this.backdate = backdate;
        this.day = day;
        this.cost = cost;
    }

   
    // Property accessors

    public long getOutid() {
        return this.outid;
    }
    
    public void setOutid(long outid) {
        this.outid = outid;
    }

    public OutRecord getOutrecord() {
        return this.outrecord;
    }
    
    public void setOutrecord(OutRecord outrecord) {
        this.outrecord = outrecord;
    }

    public String getBackdate() {
        return this.backdate;
    }
    
    public void setBackdate(String backdate) {
        this.backdate = backdate;
    }

    public long getDay() {
        return this.day;
    }
    
    public void setDay(long day) {
        this.day = day;
    }

    public long getCost() {
        return this.cost;
    }
    
    public void setCost(long cost) {
        this.cost = cost;
    }
   








}