package dao.bean;

// default package

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MotorCar generated by MyEclipse - Hibernate Tools
 */

public class MotorCar implements java.io.Serializable {

	// Fields

	private long id;

	private Driver driver;

	private String carnumber;

	private String cartype;

	private long capacity;

	private String registerdate;

	private String status;

	private String descripe;

	// Constructors

	/** default constructor */
	public MotorCar() {
	}

	/** minimal constructor */
	public MotorCar(Driver driver, String carnumber, String cartype,
			long capacity, String registerdate) {
		this.driver = driver;
		this.carnumber = carnumber;
		this.cartype = cartype;
		this.capacity = capacity;
		this.registerdate = registerdate;
	}

	/** full constructor */
	public MotorCar(Driver driver, String carnumber, String cartype,
			long capacity, String registerdate, String status, String descripe) {
		this.driver = driver;
		this.carnumber = carnumber;
		this.cartype = cartype;
		this.capacity = capacity;
		this.registerdate = registerdate;
		this.status = status;
		this.descripe = descripe;
	}

	// Property accessors

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Driver getDriver() {
		return this.driver;
	}

	public void setDriver(Driver driver) {
		this.driver = driver;
	}

	public String getCarnumber() {
		return this.carnumber;
	}

	public void setCarnumber(String carnumber) {
		this.carnumber = carnumber;
	}

	public String getCartype() {
		return this.cartype;
	}

	public void setCartype(String cartype) {
		this.cartype = cartype;
	}

	public long getCapacity() {
		return this.capacity;
	}

	public void setCapacity(long capacity) {
		this.capacity = capacity;
	}

	public String getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(String registerdate) {
		this.registerdate = registerdate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDescripe() {
		return this.descripe;
	}

	public void setDescripe(String descripe) {
		this.descripe = descripe;
	}

}