package dao.bean;

// default package

import java.util.Date;

/**
 * OutRecord generated by MyEclipse - Hibernate Tools
 */

public class OutRecord implements java.io.Serializable {

	// Fields

	private long id;

	private ApplicationRecord apprecord;

	private User user;

	private MotorCar motorcar;

	private String outdate;
	
	private long status;

	// Constructors

	/** default constructor */
	public OutRecord() {
	}

	/** minimal constructor */
	public OutRecord(ApplicationRecord apprecord, User user, MotorCar motorcar,
			String outdate) {
		this.apprecord = apprecord;
		this.user = user;
		this.motorcar = motorcar;
		this.outdate = outdate;
	}


	// Property accessors

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ApplicationRecord getApprecord() {
		return this.apprecord;
	}

	public void setApprecord(ApplicationRecord apprecord) {
		this.apprecord = apprecord;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public MotorCar getMotorcar() {
		return this.motorcar;
	}

	public void setMotorcar(MotorCar motorcar) {
		this.motorcar = motorcar;
	}

	public String getOutdate() {
		return this.outdate;
	}

	public void setOutdate(String outdate) {
		this.outdate = outdate;
	}

	public long getStatus() {
		return status;
	}

	public void setStatus(long status) {
		this.status = status;
	}
	
}