package dao.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by MyEclipse - Hibernate Tools
 */

public class User implements java.io.Serializable {

	// Fields

	private long id;

	private String nickname;

	private String password;

	private String name;

	private String identitycard;

	private String passwdquestion;

	private String passwdanswer;

	private String gender;

	private long age;

	private String address;

	private String phone;

	private long power;

	private long isonline;

	private String icon;

	// Constructors

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public long getIsonline() {
		return isonline;
	}

	public void setIsonline(long isonline) {
		this.isonline = isonline;
	}

	/** default constructor */
	public User() {
	}

	/** minimal constructor */
	public User(String nickname, String password, String name,
			String identitycard, String passwdquestion, String passwdanswer,
			String gender, String address, String phone) {
		this.nickname = nickname;
		this.password = password;
		this.name = name;
		this.identitycard = identitycard;
		this.passwdquestion = passwdquestion;
		this.passwdanswer = passwdanswer;
		this.gender = gender;
		this.address = address;
		this.phone = phone;
	}

	/** full constructor */
	public User(String nickname, String password, String name,
			String identitycard, String passwdquestion, String passwdanswer,
			String gender, long age, String address, String phone, long power) {
		this.nickname = nickname;
		this.password = password;
		this.name = name;
		this.identitycard = identitycard;
		this.passwdquestion = passwdquestion;
		this.passwdanswer = passwdanswer;
		this.gender = gender;
		this.age = age;
		this.address = address;
		this.phone = phone;
		this.power = power;
	}

	// Property accessors

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIdentitycard() {
		return this.identitycard;
	}

	public void setIdentitycard(String identitycard) {
		this.identitycard = identitycard;
	}

	public String getPasswdquestion() {
		return this.passwdquestion;
	}

	public void setPasswdquestion(String passwdquestion) {
		this.passwdquestion = passwdquestion;
	}

	public String getPasswdanswer() {
		return this.passwdanswer;
	}

	public void setPasswdanswer(String passwdanswer) {
		this.passwdanswer = passwdanswer;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public long getAge() {
		return this.age;
	}

	public void setAge(long age) {
		this.age = age;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public long getPower() {
		return this.power;
	}

	public void setPower(long power) {
		this.power = power;
	}
}