/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-23-2008
 * 
 * XDoclet definition:
 * @struts.form name="findDriverByConditionForm"
 */
public class FindDriverByConditionForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** gender property */
	private String gender;

	/** cartype property */
	private String cartype;

	/** age property */
	private String age;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the gender.
	 * @return String
	 */
	public String getGender() {
		return gender;
	}

	/** 
	 * Set the gender.
	 * @param gender The gender to set
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/** 
	 * Returns the cartype.
	 * @return String
	 */
	public String getCartype() {
		return cartype;
	}

	/** 
	 * Set the cartype.
	 * @param cartype The cartype to set
	 */
	public void setCartype(String cartype) {
		this.cartype = cartype;
	}

	/** 
	 * Returns the age.
	 * @return String
	 */
	public String getAge() {
		return age;
	}

	/** 
	 * Set the age.
	 * @param age The age to set
	 */
	public void setAge(String age) {
		this.age = age;
	}
}