/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-23-2008
 * 
 * XDoclet definition:
 * @struts.form name="FindMissingPasswordForm"
 */
public class FindMissingPasswordForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userName property */
	private String userName;

	/** passwdQuestion property */
	private String passwdQuestion;

	/** passwdAnswer property */
	private String passwdAnswer;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the passwdQuestion.
	 * @return String
	 */
	public String getPasswdQuestion() {
		return passwdQuestion;
	}

	/** 
	 * Set the passwdQuestion.
	 * @param passwdQuestion The passwdQuestion to set
	 */
	public void setPasswdQuestion(String passwdQuestion) {
		this.passwdQuestion = passwdQuestion;
	}

	/** 
	 * Returns the passwdAnswer.
	 * @return String
	 */
	public String getPasswdAnswer() {
		return passwdAnswer;
	}

	/** 
	 * Set the passwdAnswer.
	 * @param passwdAnswer The passwdAnswer to set
	 */
	public void setPasswdAnswer(String passwdAnswer) {
		this.passwdAnswer = passwdAnswer;
	}
}