/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package web.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-16-2002
 * 
 * XDoclet definition:
 * @struts.form name="RegisterForm"
 */
public class RegisterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** phone property */
	private String phone;

	/** gender property */
	private String gender;

	/** age property */
	private Long age;

	/** passwdQuestion property */
	private String passwdQuestion;

	/** passwdAnswer property */
	private String passwdAnswer;

	/** passwd property */
	private String passwd;

	/** identitycar property */
	private String identitycar;

	/** address property */
	private String address;

	/** name property */
	private String name;

	/** nickName property */
	private String nickName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the gender.
	 * @return String
	 */
	public String getGender() {
		return gender;
	}

	/** 
	 * Set the gender.
	 * @param gender The gender to set
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/** 
	 * Returns the age.
	 * @return String
	 */
	public Long getAge() {
		return age;
	}

	/** 
	 * Set the age.
	 * @param age The age to set
	 */
	public void setAge(Long age) {
		this.age = age;
	}

	/** 
	 * Returns the passwdQuestion.
	 * @return String
	 */
	public String getPasswdQuestion() {
		return passwdQuestion;
	}

	/** 
	 * Set the passwdQuestion.
	 * @param passwdQuestion The passwdQuestion to set
	 */
	public void setPasswdQuestion(String passwdQuestion) {
		this.passwdQuestion = passwdQuestion;
	}

	/** 
	 * Returns the passwdAnswer.
	 * @return String
	 */
	public String getPasswdAnswer() {
		return passwdAnswer;
	}

	/** 
	 * Set the passwdAnswer.
	 * @param passwdAnswer The passwdAnswer to set
	 */
	public void setPasswdAnswer(String passwdAnswer) {
		this.passwdAnswer = passwdAnswer;
	}

	/** 
	 * Returns the passwd.
	 * @return String
	 */
	public String getPasswd() {
		return passwd;
	}

	/** 
	 * Set the passwd.
	 * @param passwd The passwd to set
	 */
	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	/** 
	 * Returns the identitycar.
	 * @return String
	 */
	public String getIdentitycar() {
		return identitycar;
	}

	/** 
	 * Set the identitycar.
	 * @param identitycar The identitycar to set
	 */
	public void setIdentitycar(String identitycar) {
		this.identitycar = identitycar;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the nickName.
	 * @return String
	 */
	public String getNickName() {
		return nickName;
	}

	/** 
	 * Set the nickName.
	 * @param nickName The nickName to set
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
}