/*
 * JSP generated by Resin-3.0.8 (built Tue, 08 Jun 2004 02:25:40 PDT)
 */

package _jsp._info;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.sql.*;

public class _grade__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=gb2312");
    request.setCharacterEncoding("GB2312");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
	if ((String) session.getAttribute("login")==null){

		String all_curPage = request.getRequestURI();//\u5f97\u5230\u5f53\u524d\u9875\u9762\u7684\u8def\u5f84\u548c\u540d\u79f0
		String all_curQueryString = request.getQueryString();//\u5f97\u5230\u5f53\u524d\u9875\u9762\u7684\u53c2\u6570

		String referer = all_curPage;
		if(all_curQueryString!=null){
			referer += "?" + all_curQueryString;
		}
	

		response.sendRedirect("../deng.jsp?referer="+java.net.URLEncoder.encode(referer));//\u4e00\u5b9a\u8981\u7f16\u7801,\u5426\u5219\u7279\u6b8a\u5b57\u7b26\u4f20\u4e0d\u8fc7\u53bb
	
	}
	

      out.write(_jsp_string1, 0, _jsp_string1.length);
      Connection con;
Statement stmt;
ResultSet rs;
Class.forName("com.mysql.jdbc.Driver");
DriverManager.registerDriver(new com.mysql.jdbc.Driver());
String dbUrl="jdbc:mysql://localhost:3306/laba?useUnicode=true&characterEncoding=GB2312";
String dbUser="root";
String dbPwd="1982o7o9";
con=java.sql.DriverManager.getConnection(dbUrl,dbUser,dbPwd);
stmt=con.createStatement();

      out.write(_jsp_string2, 0, _jsp_string2.length);
      
stmt = con.createStatement() ;
String userid=(String) session.getAttribute("userid");
rs=stmt.executeQuery("SELECT * from grade where memid='"+userid+"' order by id desc");
rs.next();

      out.write(_jsp_string3, 0, _jsp_string3.length);
      if(Integer.parseInt(rs.getString("fen"))>0&&Integer.parseInt(rs.getString("fen"))<100){
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((rs.getString("fen")));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      }else{
      out.write(_jsp_string6, 0, _jsp_string6.length);
      if(Integer.parseInt(rs.getString("fen"))>99&&Integer.parseInt(rs.getString("fen"))<200){
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((rs.getString("fen")));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      }else{
      out.write(_jsp_string3, 0, _jsp_string3.length);
      if(Integer.parseInt(rs.getString("fen"))>199&&Integer.parseInt(rs.getString("fen"))<300){
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((rs.getString("fen")));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      }else{
      out.write(_jsp_string3, 0, _jsp_string3.length);
      if(Integer.parseInt(rs.getString("fen"))>299&&Integer.parseInt(rs.getString("fen"))<400){
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((rs.getString("fen")));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      }else{
      out.write(_jsp_string3, 0, _jsp_string3.length);
      if(Integer.parseInt(rs.getString("fen"))>399&&Integer.parseInt(rs.getString("fen"))<500){
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((rs.getString("fen")));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      }else{
      out.write(_jsp_string11, 0, _jsp_string11.length);
      if(Integer.parseInt(rs.getString("fen"))>499&&Integer.parseInt(rs.getString("fen"))<600){
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((rs.getString("fen")));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      }else{
      out.write(_jsp_string11, 0, _jsp_string11.length);
      if(Integer.parseInt(rs.getString("fen"))>599&&Integer.parseInt(rs.getString("fen"))<700){
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((rs.getString("fen")));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      }else{
      out.write(_jsp_string14, 0, _jsp_string14.length);
      if(Integer.parseInt(rs.getString("fen"))>699&&Integer.parseInt(rs.getString("fen"))<800){
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((rs.getString("fen")));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      }else{
      out.write(_jsp_string11, 0, _jsp_string11.length);
      if(Integer.parseInt(rs.getString("fen"))>799&&Integer.parseInt(rs.getString("fen"))<10000){
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((rs.getString("fen")));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      }else{
      out.write(_jsp_string6, 0, _jsp_string6.length);
      if(Integer.parseInt(rs.getString("fen"))>9999){
      out.write(_jsp_string17, 0, _jsp_string17.length);
      }else{
      out.write(_jsp_string14, 0, _jsp_string14.length);
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
      }
      out.write(_jsp_string18, 0, _jsp_string18.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 1174304630)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    _caucho_line_map = new com.caucho.java.LineMap("_grade__jsp.java", "foo");
    _caucho_line_map.add("/info/checksession.jsp", 1, 32);
    _caucho_line_map.add("/info/../conn/conn.jsp", 6, 50);
    _caucho_line_map.add("/info/grade.jsp", 46, 62);
    _caucho_line_map.add(54, 69);
    _caucho_line_map.add(55, 71);
    _caucho_line_map.add(55, 73);
    _caucho_line_map.add(57, 75);
    _caucho_line_map.add(58, 77);
    _caucho_line_map.add(58, 79);
    _caucho_line_map.add(61, 81);
    _caucho_line_map.add(62, 83);
    _caucho_line_map.add(62, 85);
    _caucho_line_map.add(65, 87);
    _caucho_line_map.add(66, 89);
    _caucho_line_map.add(66, 91);
    _caucho_line_map.add(69, 93);
    _caucho_line_map.add(70, 95);
    _caucho_line_map.add(70, 97);
    _caucho_line_map.add(75, 99);
    _caucho_line_map.add(76, 101);
    _caucho_line_map.add(76, 103);
    _caucho_line_map.add(81, 105);
    _caucho_line_map.add(82, 107);
    _caucho_line_map.add(82, 109);
    _caucho_line_map.add(86, 111);
    _caucho_line_map.add(87, 113);
    _caucho_line_map.add(87, 115);
    _caucho_line_map.add(92, 117);
    _caucho_line_map.add(93, 119);
    _caucho_line_map.add(93, 121);
    _caucho_line_map.add(95, 123);
    _caucho_line_map.add(96, 125);
    _caucho_line_map.add(100, 127);
    _caucho_line_map.add(101, 129);
    _caucho_line_map.add(102, 131);
    _caucho_line_map.add(103, 133);
    _caucho_line_map.add(104, 135);
    _caucho_line_map.add(105, 137);
    _caucho_line_map.add(106, 139);
    _caucho_line_map.add(107, 141);
    _caucho_line_map.add(108, 143);
    _caucho_line_map.add(109, 145);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("info/grade.jsp"), "O6omTTEQG5wGz4UBKnfFUg==", false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("info/checksession.jsp"), "bjMdX2FM/Nyg5W8bXNL90A==", false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("conn/conn.jsp"), "Y8eOeqaPTEc4uE5RVs4RUg==", false);
    _caucho_depends.add(depend);
  }

  private final static char []_jsp_string17;
  private final static char []_jsp_string18;
  private final static char []_jsp_string5;
  private final static char []_jsp_string11;
  private final static char []_jsp_string16;
  private final static char []_jsp_string3;
  private final static char []_jsp_string15;
  private final static char []_jsp_string13;
  private final static char []_jsp_string12;
  private final static char []_jsp_string0;
  private final static char []_jsp_string10;
  private final static char []_jsp_string9;
  private final static char []_jsp_string8;
  private final static char []_jsp_string7;
  private final static char []_jsp_string4;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string14;
  private final static char []_jsp_string6;
  static {
    _jsp_string17 = "\r\n<a href=\"../info/gradeindex.jsp\" onMouseOver=popup(1) onMouseOut=kill() target=\"_blank\"><img src=../info/images/grade10.gif alt=\"\u4f01\u5bcc\u901a\u4f1a\u5458\" border=0></a>".toCharArray();
    _jsp_string18 = "\r\n\r\n\r\n\r\n</body>\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string5 = "\" border=0></a>".toCharArray();
    _jsp_string11 = "\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string16 = "\r\n<a href=\"../info/gradeindex.jsp\" onMouseOver=popup(1) onMouseOut=kill() target=\"_blank\"><img src=../info/images/grade9.gif alt=\"\u8bda\u4fe1\u6307\u6570:9\u661f;\u79ef\u5206:".toCharArray();
    _jsp_string3 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string15 = "\r\n<a href=\"../info/gradeindex.jsp\" onMouseOver=popup(1) onMouseOut=kill() target=\"_blank\"><img src=../info/images/grade8.gif alt=\"\u8bda\u4fe1\u6307\u6570:8\u661f;\u79ef\u5206:".toCharArray();
    _jsp_string13 = "\r\n<a href=\"../info/gradeindex.jsp\" onMouseOver=popup(1) onMouseOut=kill() target=\"_blank\"><img src=../info/images/grade7.gif alt=\"\u8bda\u4fe1\u6307\u6570:7\u661f;\u79ef\u5206:".toCharArray();
    _jsp_string12 = "\r\n<a href=\"../info/gradeindex.jsp\" onMouseOver=popup(1) onMouseOut=kill() target=\"_blank\"><img src=../info/images/grade6.gif alt=\"\u8bda\u4fe1\u6307\u6570:6\u661f;\u79ef\u5206:".toCharArray();
    _jsp_string0 = "\r\n".toCharArray();
    _jsp_string10 = "\r\n<a href=\"../info/gradeindex.jsp\" onMouseOver=popup(1) onMouseOut=kill() target=\"_blank\"><img src=../info/images/grade5.gif alt=\"\u8bda\u4fe1\u6307\u6570:5\u661f;\u79ef\u5206:".toCharArray();
    _jsp_string9 = "\r\n<a href=\"../info/gradeindex.jsp\" onMouseOver=popup(1) onMouseOut=kill() target=\"_blank\"><img src=../info/images/grade4.gif alt=\"\u8bda\u4fe1\u6307\u6570:4\u661f;\u79ef\u5206:".toCharArray();
    _jsp_string8 = "\r\n<a href=\"../info/gradeindex.jsp\" onMouseOver=popup(1) onMouseOut=kill() target=\"_blank\"><img src=../info/images/grade3.gif alt=\"\u8bda\u4fe1\u6307\u6570:3\u661f;\u79ef\u5206:".toCharArray();
    _jsp_string7 = "\r\n<a href=\"../info/gradeindex.jsp\" onMouseOver=popup(1) onMouseOut=kill() target=\"_blank\"><img src=../info/images/grade2.gif alt=\"\u8bda\u4fe1\u6307\u6570:2\u661f;\u79ef\u5206:".toCharArray();
    _jsp_string4 = "\r\n<a href=\"../info/gradeindex.jsp\" onMouseOver=popup(1) onMouseOut=kill() target=\"_blank\"><img src=../info/images/grade1.gif alt=\"\u8bda\u4fe1\u6307\u6570:1\u661f;\u79ef\u5206:".toCharArray();
    _jsp_string2 = "\r\n\r\n\r\n<style type=\"text/css\">\r\nBODY { OVERFLOW-X: hidden; OVERFLOW: scroll}\r\n.DEK { Z-INDEX: 200; VISIBILITY: hidden; POSITION: absolute} \r\n</style>\r\n<body>\r\n<div class=dek id=dek>\r\n<SCRIPT type=text/javascript language=\"\">\r\nXoffset= 0;    // modify these values to ...\r\nYoffset= 20;    // change the popup position.\r\nmyImg= new Array()\r\nmyImg[1]=\"../info/images/help.gif\"\r\nvar nav,old,iex=(document.all),yyy=-1000;\r\nif(navigator.appName==\"Netscape\"){(document.layers)?nav=true:old=true;}\r\nif(!old){\r\nvar skn=(nav)?document.dek:dek.style;\r\nif(nav)document.captureEvents(Event.MOUSEMOVE);\r\ndocument.onmousemove=get_mouse;\r\n}\r\nfunction popup(i){\r\nvar content=\"<img src='\"+ myImg[i]+\"'>\";\r\nif(old){alert(msg);return;} \r\nelse{yyy=Yoffset;\r\nif(nav){skn.document.write(content);skn.document.close();skn.visibility=\"visible\"}\r\nif(iex){document.all(\"dek\").innerHTML=content;skn.visibility=\"visible\"}\r\n}\r\n}\r\nfunction get_mouse(e){\r\nvar x=(nav)?e.pageX:event.x+document.body.scrollLeft;skn.left=x+Xoffset;\r\nvar y=(nav)?e.pageY:event.y+document.body.scrollTop;skn.top=y+yyy;\r\n}\r\nfunction kill(){\r\nif(!old){yyy=-1000;skn.visibility=\"hidden\";}\r\n}\r\n//-->\r\n</SCRIPT>\r\n</div>\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n\r\n\r\n<link rel=\"stylesheet\" href=\"../conn/laba.css\" type=\"text/css\">\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string14 = "\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string6 = "\r\n\r\n".toCharArray();
  }
}
