/*
 * JSP generated by Resin-3.0.8 (built Tue, 08 Jun 2004 02:25:40 PDT)
 */

package _jsp._info;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.util.Date;
import java.text.*;

public class _how__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=gb2312");
    request.setCharacterEncoding("GB2312");
    try {
      
	if ((String) session.getAttribute("login")==null){

		String all_curPage = request.getRequestURI();//\u00b5\u00c3\u00b5\u00bd\u00b5\u00b1\u00c7\u00b0\u00d2\u00b3\u00c3\u00e6\u00b5\u00c4\u00c2\u00b7\u00be\u00b6\u00ba\u00cd\u00c3\u00fb\u00b3\u00c6
		String all_curQueryString = request.getQueryString();//\u00b5\u00c3\u00b5\u00bd\u00b5\u00b1\u00c7\u00b0\u00d2\u00b3\u00c3\u00e6\u00b5\u00c4\u00b2\u00ce\u00ca\u00fd

		String referer = all_curPage;
		if(all_curQueryString!=null){
			referer += "?" + all_curQueryString;
		}
	

		response.sendRedirect("../deng.jsp?referer="+java.net.URLEncoder.encode(referer));//\u00d2\u00bb\u00b6\u00a8\u00d2\u00aa\u00b1\u00e0\u00c2\u00eb,\u00b7\u00f1\u00d4\u00f2\u00cc\u00d8\u00ca\u00e2\u00d7\u00d6\u00b7\u00fb\u00b4\u00ab\u00b2\u00bb\u00b9\u00fd\u00c8\u00a5
	
	}
	

      out.write(_jsp_string0, 0, _jsp_string0.length);
      Connection con;
Statement stmt;
ResultSet rs;
Class.forName("com.mysql.jdbc.Driver");
DriverManager.registerDriver(new com.mysql.jdbc.Driver());
String dbUrl="jdbc:mysql://localhost:3306/laba?useUnicode=true&characterEncoding=GB2312";
String dbUser="root";
String dbPwd="1982o7o9";
con=java.sql.DriverManager.getConnection(dbUrl,dbUser,dbPwd);
stmt=con.createStatement();

      out.write(_jsp_string1, 0, _jsp_string1.length);
      Date currTime = new Date();
  SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd",Locale.US);
  String time=new String(formatter.format(currTime).getBytes("iso-8859-1"));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      session.setAttribute("time",time);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      String fbtime=(String) session.getAttribute("time");
      out.write(_jsp_string3, 0, _jsp_string3.length);
      
int i=0 ,k=0, Results=0 ,s;

stmt = con.createStatement() ;
String userid=(String) session.getAttribute("userid");
rs=stmt.executeQuery("SELECT count(*) from dingzhisj  where memid='"+userid+"' order by id desc");
while(rs.next()) k = rs.getInt(1) ;

stmt = con.createStatement() ;
String sql1="SELECT * from dingzhisj where memid='"+userid+"' order by id desc";
ResultSet rs1=stmt.executeQuery(sql1) ;
while(rs1.next()&i<k){
i++ ;

s=0;
String gjz=rs1.getString("gjz");
String lei=rs1.getString("lei");
String dq=rs1.getString("dq");

stmt = con.createStatement() ;
String sql2="SELECT count(*) from sjxx  where (topic like '%"+gjz+"%' or content like '%"+gjz+"%') and  fbtime='"+fbtime+"'  and  lei='"+lei+"' order by id desc";
ResultSet rs2=stmt.executeQuery(sql2) ;
while(rs2.next()) s = rs2.getInt(1) ;

Results = Results + s;

}

      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((Results));
      out.write(_jsp_string5, 0, _jsp_string5.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 1174304630)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    _caucho_line_map = new com.caucho.java.LineMap("_how__jsp.java", "foo");
    _caucho_line_map.add("/info/checksession.jsp", 1, 33);
    _caucho_line_map.add("/info/../conn/conn.jsp", 6, 51);
    _caucho_line_map.add("/info/../conn/time.jsp", 6, 63);
    _caucho_line_map.add(9, 67);
    _caucho_line_map.add("/info/how.jsp", 5, 69);
    _caucho_line_map.add(9, 71);
    _caucho_line_map.add(38, 100);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("info/how.jsp"), "gypk417yyg09ELhRhUmO3A==", false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("info/checksession.jsp"), "bjMdX2FM/Nyg5W8bXNL90A==", false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("conn/conn.jsp"), "Y8eOeqaPTEc4uE5RVs4RUg==", false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("conn/time.jsp"), "ihl6LzOAw9TTH3Ur9mELWQ==", false);
    _caucho_depends.add(depend);
  }

  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  private final static char []_jsp_string5;
  private final static char []_jsp_string4;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  static {
    _jsp_string3 = "\r\n<link href=\"../conn/laba.css\" rel=\"stylesheet\" type=\"text/css\">\r\n<BODY leftMargin=0 marginwidth=\"0\"  topMargin=0 bgcolor=ffffd6>\r\n\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<link rel=\"stylesheet\" href=\"../conn/laba.css\" type=\"text/css\">\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string5 = "</font></a></center>".toCharArray();
    _jsp_string4 = "\r\n\r\n<center><A href=mysj.jsp class=C   target=\"_blank\"><font color=red>".toCharArray();
    _jsp_string2 = "\r\n".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
